//! Plan-diff conformance — the Rust `diff_plans()` reproduces the TypeScript
//! reference's diff for each fixture (a manifest planned under two option sets),
//! generated by scripts/gen-rust-fixtures.mjs.

use kcp_planner::{diff_plans, parse_manifest, plan, PlanDiff, PlanOptions};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct DiffFixture {
    name: String,
    manifest: String,
    task: String,
    a: PlanOptions,
    b: PlanOptions,
    expect: PlanDiff,
}

fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/diff")
}

#[test]
fn all_diff_fixtures_pass() {
    let pattern = dir().join("*.json");
    let mut count = 0;
    let mut failures = Vec::new();
    for entry in glob::glob(pattern.to_str().unwrap()).expect("glob") {
        let path = entry.expect("entry");
        let fx: DiffFixture = serde_json::from_str(&std::fs::read_to_string(&path).unwrap())
            .unwrap_or_else(|e| panic!("parse {}: {}", path.display(), e));
        let manifest = parse_manifest(&fx.manifest, Some(&fx.name)).expect("manifest");
        let pa = plan(&manifest, &fx.task, &fx.a);
        let pb = plan(&manifest, &fx.task, &fx.b);
        let actual = diff_plans(&pa, &pb);
        if actual != fx.expect {
            failures.push(format!(
                "\n=== {} ===\n  expected: {}\n  actual:   {}",
                fx.name,
                serde_json::to_string(&fx.expect).unwrap(),
                serde_json::to_string(&actual).unwrap()
            ));
        }
        count += 1;
    }
    assert!(count >= 3, "expected >= 3 diff fixtures, found {}", count);
    assert!(failures.is_empty(), "{} diff fixture(s) failed:{}", failures.len(), failures.join(""));
}
